In [13]:
import numpy as np

In [14]:
#define neighbors
borderI = [-1, 0, 0, 1]
borderJ = [0, -1, 1, 0]
num = len(borderI)

"""
Search for neighbors
The main idea is when we find the part of island, we detected all parts of island
and then erase them. So we can't find this island twice.
""" 
def save(i, j):
    return (i >= 0 and i < N and
            j >= 0 and j < M and
            matrix[i][j] == 1)

def erase(i, j):
    for k in range(num):        
        if save(i+borderI[k], j+borderJ[k]):
            matrix[i+borderI[k]][j+borderJ[k]] = 0
            erase(i+borderI[k], j+borderJ[k])

In [15]:
#Matrix definition
N = int(input("Number of rows(N): "))
M = int(input("Number of colomns(M): "))
print("Matrix elements: ")
val = list(map(int, input().split()))
matrix = np.array(val).reshape(N,M)

#Show matrix
print("\nMatrix look:")
for i in range(N):
  print(matrix[i])

#Count the number of islands
count = 0
for i in range(N):
  for j in range(M):
    if matrix[i][j] == 1:
      matrix[i][j] =0
      erase(i,j)
      count += 1
           
print("\nOutput: ", count) 


Number of rows(N): 3
Number of colomns(M): 4
Matrix elements: 
0 0 0 1 0 0 1 1 0 1 0 1

Matrix look:
[0 0 0 1]
[0 0 1 1]
[0 1 0 1]

Output:  2
